// demo-data.js — fake profiles for demo/preview mode

const DEMO_PROFILES = [
  {
    id: 'demo-1',
    name: 'Jordan',
    initial: 'J',
    activities: ['cafe', 'study', 'walk'],
    group_size: 'small',
    place_vibe: 'quiet',
    plan_style: 'ahead',
    duration: 'medium',
    timing: ['afternoon', 'evening'],
    time_of_day: 'depends',
    best_days: ['tue', 'wed', 'thu'],
    openness: 4,
    follow_through: 4,
    intent: 'things_together',
    energy_level: 'okay',
    talk_listen: 'balanced',
    recharge: 'either',
    silence: 'love',
    distance: 'anywhere',
    notice: 'hour',
    group_pref: 'small',
    interests: ['music', 'film', 'books'],
    current_vibe: 'caffeinated and confused',
    surprised_yourself: 'finished a book in one sitting',
    semester_goal: 'find a study spot I actually like',
  },
  {
    id: 'demo-2',
    name: 'Morgan',
    initial: 'M',
    activities: ['cafe', 'gym', 'offcampus'],
    group_size: '1on1',
    place_vibe: 'chill',
    plan_style: 'dayof',
    duration: 'long',
    timing: ['morning', 'afternoon', 'weekends'],
    time_of_day: 'morning',
    best_days: ['sat', 'sun', 'fri'],
    openness: 5,
    follow_through: 5,
    intent: 'new_friends',
    energy_level: 'great',
    talk_listen: 'talk',
    recharge: 'more',
    silence: 'neutral',
    distance: 'offcampus',
    notice: 'none',
    group_pref: 'one_on_one',
    interests: ['travel', 'food', 'sports'],
    current_vibe: 'ready for anything',
    surprised_yourself: 'ran 5k without stopping',
    semester_goal: 'explore every coffee shop within 2 miles',
  },
  {
    id: 'demo-3',
    name: 'Sam',
    initial: 'S',
    activities: ['study', 'walk', 'movie'],
    group_size: 'either',
    place_vibe: 'anywhere',
    plan_style: 'ahead',
    duration: 'medium',
    timing: ['between', 'evening', 'latenight'],
    time_of_day: 'night',
    best_days: ['mon', 'wed', 'fri'],
    openness: 3,
    follow_through: 3,
    intent: 'off_phone',
    energy_level: 'okay',
    talk_listen: 'listen',
    recharge: 'alone',
    silence: 'love',
    distance: 'anywhere',
    notice: 'hours',
    group_pref: 'small',
    interests: ['film', 'gaming', 'tech'],
    current_vibe: 'quietly overthinking',
    surprised_yourself: 'talked to a stranger first',
    semester_goal: 'watch every film on my watchlist',
  },
  {
    id: 'demo-4',
    name: 'Alex',
    initial: 'A',
    activities: ['food', 'cafe', 'walk', 'study'],
    group_size: 'small',
    place_vibe: 'quiet',
    plan_style: 'dayof',
    duration: 'medium',
    timing: ['morning', 'between', 'afternoon', 'evening'],
    time_of_day: 'depends',
    best_days: ['tue', 'thu', 'fri', 'sat'],
    openness: 4,
    follow_through: 4,
    intent: 'things_together',
    energy_level: 'great',
    talk_listen: 'balanced',
    recharge: 'either',
    silence: 'neutral',
    distance: 'anywhere',
    notice: 'hour',
    group_pref: 'small',
    interests: ['books', 'food', 'wellness'],
    current_vibe: 'showing up consistently',
    surprised_yourself: 'went to the dining hall alone and it was fine',
    semester_goal: 'use the campus gym more than twice a week',
  },
];

function getDemoScores(userProfile) {
  if (!userProfile || !userProfile.activities) return DEMO_PROFILES;
  return DEMO_PROFILES.map(p => ({
    ...p,
    score: calculateCompatibility(userProfile, p),
  })).sort((a, b) => b.score - a.score);
}
